language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - ruby-head
  - rubinius-3.86
  - jruby
install: gem install rest-client lager json minitest
script: rake test
sudo: required # for rubinius-3.86 container update
